#!/usr/bin/env bash
# Generate infra/litellm/.env from infra/litellm/.env.example.
# Run once: bash scripts/setup-env.sh
# After this, infra/litellm/.env is gitignored;
# infra/litellm/.env.example is the committed template.
set -euo pipefail

cd "$(dirname "$0")/.."

ENV_PATH="infra/litellm/.env"
EXAMPLE_PATH="infra/litellm/.env.example"

if [[ -f "$ENV_PATH" ]]; then
  echo "$ENV_PATH already exists; not overwriting. Edit it manually or delete it." >&2
  exit 0
fi

# Pick strong random keys.
gen() { openssl rand -hex 32; }

LITELLM_MASTER_KEY="sk-litellm-master-$(gen)"
FAKE_PROVIDER_DUMMY_KEY="dummy-key-injected-at-egress"
FAKE_PROVIDER_REAL_KEY="sk-real-provider-$(gen)"
FAKE_PROVIDER_API_BASE="http://127.0.0.1:8082/v1"

cat > "$ENV_PATH" <<EOF
# Generated by scripts/setup-env.sh. Do not commit.
# This file is read by the host-side egress proxy only.
# It is NOT mounted into the LiteLLM process.
LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
FAKE_PROVIDER_API_BASE=${FAKE_PROVIDER_API_BASE}
FAKE_PROVIDER_DUMMY_KEY=${FAKE_PROVIDER_DUMMY_KEY}
FAKE_PROVIDER_REAL_KEY=${FAKE_PROVIDER_REAL_KEY}
EOF

chmod 600 "$ENV_PATH"
echo "Wrote $ENV_PATH (mode 600)."
echo "Run: bash scripts/start.sh"
