# workestrate-config: {{ config_name }}

This is a workestrate configuration repo, generated by
`workestrate config new`.

## Structure

```
workestrate.toml     # workload definitions + secrets schema
.env.enc             # SOPS-encrypted secrets (created by setup-secrets)
.sops.yaml           # SOPS config (age recipients + creation rules)
.env.example         # auto-generated schema (run `workestrate generate-env-example`)
infra/litellm/       # LiteLLM config values (config.yaml, models.yaml)
agents/*/config/     # agent config files (models.json, settings.json, etc.)
```

## Secrets & env (the model in three lines)

Env bindings default to the **placeholder** — workloads never see a real
credential unless you opt in. The real value in-sandbox is an explicit
`bound = "guest"` on the binding, reserved for workloads that **verify** the
credential (e.g. litellm itself). `secret` appears at a binding only when
**renaming** (env name ≠ secret ID); same-name bindings are just `KEY = true`.

## Setup

1. Generate your age key (if not already done):
   ```bash
   age-keygen -o ~/.config/sops/age/ai-workbench-secrets.txt
   age-keygen -y ~/.config/sops/age/ai-workbench-secrets.txt  # print public key
   ```

2. Update `.sops.yaml` with your public key (replace `age1PLACEHOLDER` if the
   scaffold could not derive it automatically).

3. Initialize encrypted secrets:
   ```bash
   setup-secrets --config {{ config_name }} init
   ```

4. Verify:
   ```bash
   workestrate validate-config
   workestrate check
   ```

## Updating from the template

This repo was created with `workestrate config new`. To pull in template
improvements via copier (the `.copier-answers.yml` sidecar enables this):
```bash
copier update
```
