#:schema https://raw.githubusercontent.com/georgrybski/ai-workbench/main/schemas/workestrate.schema.json

schema_version = 1

# workestrate config: {{ config_name }}
# Generated by `workestrate config new`.
# Edit this file to define your workloads, secrets, and overrides.

# ─── Secret definitions ────────────────────────────────────────────────────
# These define the schema for your encrypted secrets (.env.enc).
# The env_var names must match the core policy.rs SECRET_HOST_BINDINGS.

[secrets.LITELLM_MASTER_KEY]
env_var = "LITELLM_MASTER_KEY"
hosts = ["host.microsandbox.internal"]
required = true
description = "LiteLLM proxy authentication."

[secrets.LITELLM_AUTH]
source = "LITELLM_MASTER_KEY"
exposed_as = "OPENAI_API_KEY"

[secrets.OPENROUTER_API_KEY]
env_var = "OPENROUTER_API_KEY"
hosts = ["openrouter.ai"]
required = true
description = "OpenRouter provider key."

[secrets.KIMI_CODE_API_KEY]
env_var = "KIMI_CODE_API_KEY"
hosts = ["api.kimi.com"]
required = true
description = "Kimi for Coding provider key."

[secrets.NEURALWATT_API_KEY]
env_var = "NEURALWATT_API_KEY"
hosts = ["api.neuralwatt.com"]
required = true
description = "Neuralwatt provider key."

[secrets.MINIMAX_CODING_API_KEY]
env_var = "MINIMAX_CODING_API_KEY"
hosts = ["api.minimax.io"]
required = true
description = "MiniMax Coding provider key."

[secrets.GITHUB_TOKEN]
env_var = "GITHUB_TOKEN"
hosts = ["github.com", "api.github.com"]
required = false
description = "GitHub PAT for agent git/API access."

[secrets.ODYSSEUS_ADMIN_PASSWORD]
env_var = "ODYSSEUS_ADMIN_PASSWORD"
hosts = []
required = true
placeholder = "change_me_before_first_boot"
description = "Odysseus admin login password."

# ─── Workload definitions ──────────────────────────────────────────────────
# Add [workloads.<name>] tables here. See:
# https://github.com/georgrybski/ai-workbench/blob/main/docs/migration/20-target-system-spec.md
#
# Example minimal agent workload:
# [workloads.my-agent]
# kind = "agent"
# image = { recipe = "registry", ref = "node:24-bookworm-slim" }
# workdir = "/work"
# cpus = 2
# memory_mib = 2048
# command = ["my-agent"]
# log_stop_errors = false
#
# [[workloads.my-agent.mounts]]
# host = "${CWD}"
# guest = "/work"
# read_only = false
#
# [workloads.my-agent.network]
# default_deny = true
#
# [[workloads.my-agent.network.egress]]
# recipe = "agent_base"
