#:schema ./schemas/workestrate.schema.json

schema_version = 1

# workestrate config: {{ config_name }}
# Generated by `workestrate config new`.
# Edit this file to define your workloads, secrets, and overrides.

# ─── Secret definitions ────────────────────────────────────────────────────
# These define the schema for your encrypted secrets (.env.enc) — a pure
# catalog of each credential's intrinsic properties. `allowed_hosts` entries
# must come from the core egress allowlist (policy.rs ALLOWED_EGRESS_HOSTS);
# there is no core per-secret table — any secret you declare may bind
# allowlisted hosts.
#
# A definition says NOTHING about how any workload sees the value. Exposure
# is declared per workload, at the env binding site:
#   - bindings default to the PLACEHOLDER (least exposure): the workload sees
#     a known-bad value; the real value is substituted by the egress rewrite
#     only for hosts in `allowed_hosts` (omitted = deny-all).
#   - the real value in-sandbox is an explicit `bound = "guest"` opt-in on
#     the binding, reserved for workloads that VERIFY the credential (e.g.
#     a proxy service verifying its callers).

# Generic example secrets — replace with your own credentials.
[secrets.EXAMPLE_API_KEY]
env_var = "EXAMPLE_API_KEY"
required = false

[secrets.GITHUB_TOKEN]
env_var = "GITHUB_TOKEN"
allowed_hosts = ["github.com", "api.github.com"]
required = false

# ─── Workload definitions ──────────────────────────────────────────────────
# Add [workloads.<name>] tables here. See:
# https://github.com/georgrybski/ai-workbench/blob/main/docs/migration/20-target-system-spec.md
#
# Example minimal agent workload. Env map value forms (spec 16):
#   KEY = "value"                        literal
#   KEY = true                           host-bound placeholder for secret KEY
#                                        (the default, least-exposure posture —
#                                        the egress rewrite substitutes the real
#                                        value only for `allowed_hosts`)
#   KEY = { secret = "ID" }              same, but RENAMED (env name != secret
#                                        ID); `secret` is written ONLY when
#                                        renaming
#   KEY = { bound = "guest" }            the REAL value in-sandbox — the explicit
#                                        opt-in, reserved for workloads that
#                                        verify the credential
# [workloads.my-agent]
# kind = "agent"
# image = { recipe = "registry", ref = "node:24-bookworm-slim" }
# workdir = "/work"
# cpus = 2
# memory_mib = 2048
# command = ["my-agent"]
# log_stop_errors = false
#
# [workloads.my-agent.env]
# MY_FLAG = "1"
# GITHUB_TOKEN = true                    # placeholder; agent never sees the real token
# # GITHUB_TOKEN = { bound = "guest" }   # only if my-agent VERIFIES the token itself
#
# [[workloads.my-agent.mounts]]
# host = "${CWD}"
# guest = "/work"
# read_only = false
#
# [workloads.my-agent.network]
# default_deny = true
#
# [[workloads.my-agent.network.egress]]
# recipe = "agent_base"

# ─── Mount policy (spec 22) ────────────────────────────────────────────────
# Optional [policy.mounts] block (global) and per-mount `policy = { ... }`
# entries. See spec 22 for the full read/write deny/allow + final vocabulary.
# Entries are plain patterns (relaxable by default) or
# { pattern = "...", final = true } to freeze an entry against later scopes.
# Mount-row sugar: `read.deny` / `write.deny` dotted keys also work directly
# on a [[workloads.<name>.mounts]] row.
# [policy.mounts.read]
# deny = ["**/.env", "**/.ssh/**"]
# allow = ["**/.env.example"]           # carve-out: readable again
# # a FINAL read.deny is operator-scope only (home registry / overrides.toml);
# # it compiles to the protect bucket (hidden AND untouchable):
# # deny = [..., { pattern = "**/.secret", final = true }]
# [policy.mounts.write]
# deny = ["**/.secret/**"]
# allow = ["**/.tmp/**"]
