#:schema ./schemas/workestrate.schema.json

schema_version = 2

# workestrate config: {{ config_name }}
# Generated by `workestrate config new`.
# Edit this file to define your workloads, secrets, and overrides.

# ─── Secret definitions ────────────────────────────────────────────────────
# These define the schema for your encrypted secrets (.env.enc).
# The env_var names must match the core policy.rs SECRET_HOST_BINDINGS.
#
# delivery (default "host_bound") selects how a secret reaches the sandbox:
#   host_bound: injected only for the declared egress `hosts` (omitted hosts
#               = deny-all; secure-by-default).
#   env:        exposed as a plain sandbox env var (`hosts` must be absent;
#               reachability is governed by egress rules).

[secrets.LITELLM_MASTER_KEY]
env_var = "LITELLM_MASTER_KEY"
delivery = "env"
required = true

[secrets.OPENROUTER_API_KEY]
env_var = "OPENROUTER_API_KEY"
hosts = ["openrouter.ai"]
required = true

[secrets.KIMI_CODE_API_KEY]
env_var = "KIMI_CODE_API_KEY"
hosts = ["api.kimi.com"]
required = true

[secrets.NEURALWATT_API_KEY]
env_var = "NEURALWATT_API_KEY"
hosts = ["api.neuralwatt.com"]
required = true

[secrets.MINIMAX_CODING_API_KEY]
env_var = "MINIMAX_CODING_API_KEY"
hosts = ["api.minimax.io"]
required = true

[secrets.GITHUB_TOKEN]
env_var = "GITHUB_TOKEN"
hosts = ["github.com", "api.github.com"]
required = false

[secrets.ODYSSEUS_ADMIN_PASSWORD]
env_var = "ODYSSEUS_ADMIN_PASSWORD"
delivery = "env"
required = true
placeholder = "change_me_before_first_boot"

# ─── Workload definitions ──────────────────────────────────────────────────
# Add [workloads.<name>] tables here. See:
# https://github.com/georgrybski/ai-workbench/blob/main/docs/migration/20-target-system-spec.md
#
# Example minimal agent workload (env map: bare string = literal,
# { secret = "ID" } = secret binding):
# [workloads.my-agent]
# kind = "agent"
# image = { recipe = "registry", ref = "node:24-bookworm-slim" }
# workdir = "/work"
# cpus = 2
# memory_mib = 2048
# command = ["my-agent"]
# log_stop_errors = false
#
# [workloads.my-agent.env]
# MY_FLAG = "1"
# GITHUB_TOKEN = { secret = "GITHUB_TOKEN" }
#
# [[workloads.my-agent.mounts]]
# host = "${CWD}"
# guest = "/work"
# read_only = false
#
# [workloads.my-agent.network]
# default_deny = true
#
# [[workloads.my-agent.network.egress]]
# recipe = "agent_base"
